### PR TITLE
Using-Bootstrap

### PR DESCRIPTION
**Pull request by adamclasic**
This project requests students to build a replica of the news site Newsweek.com using the Bootstrap framework.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# You have put together a really wonderful project! @adamclasic 
There is one small issue you must address, the screen sizes below 768px were not taken into account and they need to. Please look into the screen sizes between 320px and 768px, compare them closely with what you currently have on your project, make the appropriate changes and request another review! I wish you the best and see you at the very top :medal_military: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi @adamclasic, congratulations on this project 👍 You did very well implementing the changes recommended by the previous reviewer 🙂 . The project is very responsive, great use of bootstrap classes. Go ahead and merge to master, do not forget to submit the project completion form

Good luck with your next project 👍 
_Happy cdoing_ 👨‍💻 
Daniel Larbi Addo

**Comment by rammazzoti2000** [comment]
Great job @adamclasic , really great looking project, I really like how you used bootstrap classes, and the responsiveness is as it supposed to be at all three main media breakpoints

**Pull request merged**
